// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Villa_API.Data;

#nullable disable

namespace Villa_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231229145341_AddedVillaToVillaNumber")]
    partial class AddedVillaToVillaNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Villa_API.Models.Villa.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<string>("Rate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 12, 29, 16, 53, 41, 559, DateTimeKind.Local).AddTicks(1969),
                            Details = "Похоже, что у вас возникает проблема с SSL-сертификатом при подключении к серверу базы данных. В вашей строке подключения к базе данных отсутствует указание на использование SSL. Попробуйте добавить параметр Encrypt=True в вашу строку подключения:",
                            ImageUrl = "https://blogger.googleusercontent.com/img/a/AVvXsEgWg40kddLWOx6d70K50ruMx4IThciIis-cnuD2vCATJTgdSDx4pgDaqGC1bHK_j_cDnwfxHPqFztcwBZRPn2Qm59JPzlMLaOxDFYGRflLjdBUGCG0vgvU9Amgpdz9FGR_FNSGPoq-2BuP3jnjzGhvraEUpIDe2mzQ6rpBai-MOyXA9_4U-lymxoQpFWbo",
                            Name = "Royal Villa",
                            Occupancy = 5,
                            Rate = "200",
                            Sqft = 550,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 12, 29, 16, 53, 41, 559, DateTimeKind.Local).AddTicks(2011),
                            Details = "Эксклюзивная резиденция отеля Conrad Maldives Rangali Island действительно не имеет аналогов. Уникальная двухуровневая вилла располагает главной спальней и ванной комнатой, которые погружены под воду на 5 метров. Это самый настоящий ультрасовременный архитектурный шедевр с “эффектом аквариума”.",
                            ImageUrl = "https://blogger.googleusercontent.com/img/a/AVvXsEiIqgEFScWGxzPoWk3ndFOFBBqpQV2Z9W9Lfmh2G-esLTkWN5OeqOb3Zk98YdAxRctNeoqVahg9QbJoDtNbu5RAgDAsiPmS3R1vn76C2HjE289RYdGnLLDz_NUg6sS_YTQzjiGrFU8uGzNUr0jsdFT0hbSeZoBZ6rXo2ik0H85hMhcvdS_GqqFf5ZRLEP0",
                            Name = "Villa 2",
                            Occupancy = 2,
                            Rate = "222",
                            Sqft = 220,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 12, 29, 16, 53, 41, 559, DateTimeKind.Local).AddTicks(2013),
                            Details = "Похоже, что у вас возникает проблема с SSL-сертификатом при подключении к серверу базы данных. В вашей строке подключения к базе данных отсутствует указание на использование SSL. Попробуйте добавить параметр Encrypt=True в вашу строку подключения:",
                            ImageUrl = "https://blogger.googleusercontent.com/img/a/AVvXsEg-t9s_PRAwhCzKgMgjd3YFZvGR2HDY2fhCBjg38QEODZKeM0bwRjsIk5V_4t2XLi3xv_8UoeW70fCT0vaCdhG_R9HdonV7rM5Yo8DxUfH8j6YAQLcRELCut9S0dw7y5UgsEuzUgux3ESXMUHrWRehMBkMJfjfuomRpVLU48p9NkhuG_mwzJkPAGNhsAao",
                            Name = "Villa 3",
                            Occupancy = 3,
                            Rate = "333",
                            Sqft = 330,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 12, 29, 16, 53, 41, 559, DateTimeKind.Local).AddTicks(2016),
                            Details = "Похоже, что у вас возникает проблема с SSL-сертификатом при подключении к серверу базы данных. В вашей строке подключения к базе данных отсутствует указание на использование SSL. Попробуйте добавить параметр Encrypt=True в вашу строку подключения:",
                            ImageUrl = "https://blogger.googleusercontent.com/img/a/AVvXsEjT0Iy17tbcAj28-NXMvfBcXIEBZdEXTxm6pu2BBIP7az6g7t7bhnEUMTj3El3l2SEWcilwOA0XV7nUZgsRTCo64Jrc3Aa6HTF9Bs4LdKzqTR6w869x2cLE1NHu7K5Rv0iJEW4bof0RIHTjeJIL1zBK-rLaO4tqhWEy4jltigNGluMeK8noxqeNEAxJ0Ts",
                            Name = "Villa 4",
                            Occupancy = 4,
                            Rate = "444",
                            Sqft = 440,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 12, 29, 16, 53, 41, 559, DateTimeKind.Local).AddTicks(2018),
                            Details = "Похоже, что у вас возникает проблема с SSL-сертификатом при подключении к серверу базы данных. В вашей строке подключения к базе данных отсутствует указание на использование SSL. Попробуйте добавить параметр Encrypt=True в вашу строку подключения:",
                            ImageUrl = "https://blogger.googleusercontent.com/img/a/AVvXsEgWZ8JURuTTdEGEvwJcKvRehAjLUqIz1gL5Epy9vOwwTv_vN1xqDB-hqebdZt7ZdInbjlaPvJlaasYisD_3xdvCdXqIAXDwohMaBlRRY6tWjIb29ftD_Lbolr7wiJy4rsdPOquwJJOvVT6sytoS6GJS8skSWoaq3IgEzZzckt14vM8jSrtfNVkAfJ_9BvU",
                            Name = "Villa 5",
                            Occupancy = 5,
                            Rate = "555",
                            Sqft = 550,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Villa_API.Models.VillaNumberModel.VillaNumber", b =>
                {
                    b.Property<int>("VillaNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("VillaNo");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaNumbers");

                    b.HasData(
                        new
                        {
                            VillaNo = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SpecialDetails = "Автор курса сука один раз",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Villa_API.Models.VillaNumberModel.VillaNumber", b =>
                {
                    b.HasOne("Villa_API.Models.Villa.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId");

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
